name: cbook
description: A Cashbook app for Nigerian business holders

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"

  # State Management
  provider: ^6.1.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # File System & Paths
  path_provider: ^2.1.1
  path: ^1.9.0
  
  # Internationalization & Dates
  intl: ^0.18.1
  
  # Charts & Graphs
  fl_chart: ^1.0.0
  
  # Image Handling
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  cached_network_image: ^3.3.0
  
  # File Sharing
  share_plus: ^11.1.0
  
  # PDF Generation
  printing: ^5.11.1
  pdf: ^3.10.2
  
  # Firebase (Optional - for cloud sync)
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.3.3
  
  # Form Validation
  form_validator: ^2.1.1
  
  # UI Enhancements
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  badges: ^3.0.3
  flutter_staggered_animations: ^1.1.0
  
  # Currency Input
  money2: ^4.0.0
  
  # Local Notifications
  flutter_local_notifications: ^19.4.1
  
  # URL Launcher
  url_launcher: ^6.1.11
  
  # Permission Handling
  permission_handler: ^12.0.1
  
  # Secure Storage
  flutter_secure_storage: ^10.0.0-beta.4
  
  # File Operations
  file_picker: ^10.3.2
  
  # Connectivity Check
  connectivity_plus: ^6.1.5
  
  # Package Info
  package_info_plus: ^8.3.1
  google_sign_in: ^7.1.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^6.0.0
  
  # Hive Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  
  # JSON Serialization
  json_serializable: ^6.7.1
  
  # Firebase Code Generation
  flutterfire_cli: ^1.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true