// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzuiNXWmZVRY7rFSh9ZubrvWWrMKQR-AI',
    appId: '1:449712382191:web:63df4dcc587391bdd37b1a',
    messagingSenderId: '449712382191',
    projectId: 'aliamo',
    authDomain: 'aliamo.firebaseapp.com',
    databaseURL: 'https://aliamo.firebaseio.com',
    storageBucket: 'aliamo.firebasestorage.app',
    measurementId: 'G-W0FYSTCFWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuK_0fwfH3aiylkfGE06fkjUi7cGaGv9o',
    appId: '1:449712382191:android:6e4a0bb3c7c3b28ed37b1a',
    messagingSenderId: '449712382191',
    projectId: 'aliamo',
    databaseURL: 'https://aliamo.firebaseio.com',
    storageBucket: 'aliamo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmcT-r6Ov0vlHQCZB75jvx00fYCFl_5z4',
    appId: '1:449712382191:ios:6a91a9a5259b1065d37b1a',
    messagingSenderId: '449712382191',
    projectId: 'aliamo',
    databaseURL: 'https://aliamo.firebaseio.com',
    storageBucket: 'aliamo.firebasestorage.app',
    iosBundleId: 'com.example.cbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmcT-r6Ov0vlHQCZB75jvx00fYCFl_5z4',
    appId: '1:449712382191:ios:6a91a9a5259b1065d37b1a',
    messagingSenderId: '449712382191',
    projectId: 'aliamo',
    databaseURL: 'https://aliamo.firebaseio.com',
    storageBucket: 'aliamo.firebasestorage.app',
    iosBundleId: 'com.example.cbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzuiNXWmZVRY7rFSh9ZubrvWWrMKQR-AI',
    appId: '1:449712382191:web:fd74a63904002857d37b1a',
    messagingSenderId: '449712382191',
    projectId: 'aliamo',
    authDomain: 'aliamo.firebaseapp.com',
    databaseURL: 'https://aliamo.firebaseio.com',
    storageBucket: 'aliamo.firebasestorage.app',
    measurementId: 'G-7CWF1YXEGR',
  );
}
